default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: adam_nlp_api_development
  hot: localhost

test:
  <<: *default
  database: adam_nlp_api_test
  host: localhost

production:
  <<: *default
  database: adam_nlp_api_production

